### ISSUE TITLE
server laat maar 1 hotspot van een categorie zien

### ISSUE THREAD

**Issue by cheunyinz** [lamartm/team33pt#12]
De preference page is bijna af alleen laat die nu 1 hotspot zien van een categorie. Bijvoorbeeld een gebruiker heeft al interesse **"Stad"** en in de database zijn er 5 hotspots die categorie **"Stad"** hebben. In plaats van dat die alle 5 hotspots laat zien laat hij maar 1 zien. Ik denk dat het komt door de findOne op **regel 84** maar ik krijg het maar niet gefixt. 

`await getUserData(dbHotspotsCollection)
    .then((hotspot) => {
      userObject.forEach((data) => {
        allQueries.push(hotspot.findOne({
            category: data
          })
          .then((results) => {
            return results
          }))
      })
    })`

![afbeelding](https://user-images.githubusercontent.com/83555076/161346700-0d9fa529-b61f-4393-97fe-efc7ac4dd192.png)

**Comment by lamartm** [comment]
Het was inderdaad door findOne, door find() te gebruiken en dan daarna toArray() krijgen we alle data die we nodig hebben, Toen was het alleen nog een kwestie van loopen door de array en voor elk data punt wat mee doen.
