### ISSUE TITLE
Aanpassingen in de Partials

### ISSUE THREAD

**Issue by Erroar** [lamartm/team33pt#15]
Hoi, is het okay als ik de partials aanpas, zodat we onze css er beter in kunnen verwerken?  Er zitten nu een paar dubbele tags in dus die zal ik ook meteen aanpassen.

**Comment by lamartm** [comment]
Tuurlijk, en zie ik dat dit beter zal gaan als we het zo doen. Push het in een aparte branch en dan kijken we hoe we het kunnen mergen
