### ISSUE TITLE
hoe voeg ik de aangepaste informatie toe aan me pull request

### ISSUE THREAD

**Issue by Hilal-Tapan** [lamartm/team33pt#9]
Had gister pull request gemaakt. Mohamed had hier feedback op gegeven en dit heb ik toegepast. Hoe voeg ik deze verwerking toe aan de pull request, zodat die gemerged kan worden?

**Comment by lamartm** [comment]
De aangepaste informatie wordt als het goed is samengevoegd met je pull request wanneer je het commit
